#!/usr/bin/env bash
# ============================================================
# run-macro.sh — auto-generated by setup-freecad-env.sh
# Run a FreeCAD Python macro from the command line.
#
# Usage:  ./run-macro.sh <script.py> [args...]
#
# Priority order:
#   1. FreeCADCmd  (FreeCAD's own Python — most compatible)
#   2. .venv/bin/python  (venv with FreeCAD path injected)
#   3. System python3  (fallback; FreeCAD modules likely missing)
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

[[ $# -eq 0 ]] && { echo "Usage: $0 <macro.py> [args...]"; exit 1; }

MACRO="${SCRIPT_DIR}/${1}"
[[ ! -f "${MACRO}" ]] && MACRO="${1}"  # allow absolute paths too
[[ ! -f "${MACRO}" ]] && { echo "Error: macro not found: ${1}"; exit 1; }

FREECAD_CMD_CANDIDATES=(
    "/Applications/FreeCAD.app/Contents/MacOS/FreeCADCmd"
    "/Applications/FreeCAD.app/Contents/MacOS/FreeCAD"
    "/Applications/FreeCAD_0.21.app/Contents/MacOS/FreeCADCmd"
    "/Applications/FreeCAD_0.21.app/Contents/MacOS/FreeCAD"
    "${HOME}/Applications/FreeCAD.app/Contents/MacOS/FreeCADCmd"
    "${HOME}/Applications/FreeCAD.app/Contents/MacOS/FreeCAD"
    "/usr/bin/freecadcmd"
    "/usr/local/bin/freecadcmd"
    "/snap/bin/freecad"
)

FREECAD_CMD=""
for c in "${FREECAD_CMD_CANDIDATES[@]}"; do
    [[ -x "${c}" ]] && FREECAD_CMD="${c}" && break
done
command -v freecadcmd &>/dev/null && FREECAD_CMD="${FREECAD_CMD:-$(command -v freecadcmd)}"

if [[ -n "${FREECAD_CMD}" ]]; then
    echo "[run] Using FreeCADCmd: ${FREECAD_CMD}"
    exec "${FREECAD_CMD}" "${MACRO}" "${@:2}"
elif [[ -x "${SCRIPT_DIR}/.venv/bin/python" ]]; then
    echo "[run] FreeCADCmd not found — using venv Python (may lack FreeCAD modules)."
    exec "${SCRIPT_DIR}/.venv/bin/python" "${MACRO}" "${@:2}"
else
    echo "[run] WARNING: Neither FreeCADCmd nor .venv found. Using system python3."
    exec python3 "${MACRO}" "${@:2}"
fi
